build:
	g++ -std=c++20 ResourceManager.cpp AConsole.cpp Config.cpp ConsoleManager.cpp MenuScreen.cpp Process.cpp ProcessScreen.cpp CPUCoreWorker.cpp Scheduler.cpp FlatMemoryAllocator.cpp main.cpp -o main
run:
	./main
